name: Build and Deploy Docker Image go application 

on: 
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code  
        uses: actions/checkout@v4    

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }}  -p ${{ secrets.DOCKER_PASSWORD}}
      
      - name: Build docker image
        run: docker build -t abhishek9041/my-go-app .

      - name: Push Image to docker hub
        run: docker push abhishek9041/my-go-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Print variables
        run: |
            echo "EC2_HOST: $EC2_HOST"
            echo "EC2_USER: $EC2_USER"
      - name : Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2.HOST }}
          EC2_USER: ${{ secrets.EC2.USER }}
        
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem deploy.sh $USER@$HOST:/home/$USER/
          ssh -i key.pem $USER@$HOST << EOF
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/abhishek9041/my-go-app:latest
            docker stop abhishek9041/my-go-app || true
            docker rm abhishek9041/my-go-app || true
            docker run -d -p 8080:8080 --name abhishek9041/my-go-app ${{ secrets.DOCKERHUB_USERNAME }}/abhishek9041/my-go-app:latest
          EOF
